### PR TITLE
(feature):SectionComponent

### PR DESCRIPTION
**Pull request by claraabk**
##What I did

-  Created a component to use in 'about us' section
-  Exported the component to the main index of the component paste

#How to test

1. Open the terminal and go to the folder of this project

2. In terminal:
 

> `git checkout develop`
> `git pull`
> `git checkout feature/SectionComponent`
> `git pull origin feature/SectionComponent`

4. In VScode open `components ` and `SectionComponent`

5. Read the changed files section on GitHub

6. Test the things that you think are worth testing, even the ones that are not in this description

- Check if the component is working 
- Test in the index file using props 
- Test the section as 'SectionDefault' and 'invert'

### CODE REVIEW

**Review by gabrielapinheiroc — DISMISSED** [review]
Great job!

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
It's very greate, just add a margin between the props.children and content

**Review by GUIBA4 — DISMISSED** [review]
Greate job!

**Review by eliab2107 — DISMISSED** [review]
great job!

**Review by gabrielapinheiroc — DISMISSED** [review]
everything okay

**Review by GUIBA4 — DISMISSED** [review]

**Review by gabrielapinheiroc — DISMISSED** [review]
okay

**Pull request merged**
