### PR TITLE
(feature/footer): Created footer section

### PR DESCRIPTION
**Pull request by eliab2107**
#What I did:

I created a footer section

#How to test

Open the terminal and go to this project folder

At the terminal:

git checkout development
git pull
git checkout feature / footer
git pull origin feature / footer

In VScode, open the pages and footer.

Read the changed files section on GitHub.

Test the things you think are worth testing, even the ones that aren't in this description.

Test if the page works within the expected standards
Test that elements are positioned correctly
Test if the style.css it's correct.

### CODE REVIEW

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
You have just a some fix to do

- [ ] Import all svg and images in assets no in footer folder
- [ ] chagen the name of section, put something liker "Footer" no "fotercomponent"
- [ ] in css style you use  a position absolute, and you have to use a display flez ou something like that
- [ ] use width 100%
- [ ] everything in your footer it's very big, try reduce 
- [ ] reduce the height of the footer to

**Review by claraabk — CHANGES_REQUESTED** [review]
reduce height of the beackground image and fix the margin between texts

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
- [ ] Try use display flex for position the itens in footer instead bottom and left
- [ ] pass the class in css with .  instead #

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
put san serif in font family
alin the photos with the text

**Review by gabrielapinheiroc — DISMISSED** [review]
Good job!

**Review by GUIBA4 — APPROVED** [review]

**Pull request merged**
