### PR TITLE
(feature/add_buton): component and style of buttons

### PR DESCRIPTION
**Pull request by eliab2107**
#What I did : 
I created the button component that will be used in the "navbar" and "contact" sections
In "pages/style.css" I added a setting to call the "B_navbar" div that contains the buttons that will be used in the "navbar" section

#How to test

Open the terminal and go to the folder of this project

In terminal:

git checkout develop
git pull
git checkout feature/add_button
git pull origin feature/add_button

In VScode open <components> and <ButtonComponent>.

Read the changed files section on GitHub.

Test the things that you think are worth testing, even the ones that are not in this description.

Test that the buttons have all the properties they need
Test that divs are organized correctly and readably
Test if style.css is correct.

### CODE REVIEW

**Review by claraabk — CHANGES_REQUESTED** [review]
great! dont forget to import the font to css file

**Review by gabrielapinheiroc — DISMISSED** [review]
Great job!

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
Nice work, but you have some changes to do.

- [x] import component button in component index
- [x] you are not using props for your button component
- [x] you create a class for each button in page, but you have just 2 kinds of buttons

**Review by GUIBA4 — APPROVED** [review]
Nice!

**Review by claraabk — APPROVED** [review]
ok!

**Review by gabrielapinheiroc — APPROVED** [review]
everything okay

**Pull request merged**
