### PR TITLE
(Feature): i created the card component

### PR DESCRIPTION
**Pull request by gabrielapinheiroc**
#What I did :  CARD COMPONENT 

I created a card type component to be used in  the 'about us' , 'what we do' ,  'suppliers' and 'contact ' section. 
I exported this component to the main index of the component paste . 

#How to test

Open the terminal and go to the folder of this project

In terminal:

git checkout develop
git pull
git checkout feature/component_card
git pull origin feature/component_card

In VScode open components and card.

Read the changed files section on GitHub.

Test the things that you think are worth testing, even the ones that are not in this description.

- Test if the component is working for the different usages ;
- Test in the index file using props (differents imagens type and texts); 
- Test if the style.css it's correct.

### CODE REVIEW

**Review by claraabk — DISMISSED** [review]
working as expected!

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
Nice job, but you have to fix some things in your component!

- [ ] you are using image props of a wrong shape, you just have to use like that "src={props.image}
- [ ] you put positions absolut without necessity
- [ ] retry create the css using display

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
Very greate, just somethings to improve 

- [ ] try use the font withoud san serif
- [ ] put a shadow box in component
- [ ] change the folder name for "Card"

**Review by GUIBA4 — APPROVED** [review]
Nice job!

**Review by GUIBA4 — CHANGES_REQUESTED** [review]
Change the name of folder

**Review by GUIBA4 — DISMISSED** [review]
greate

**Review by claraabk — CHANGES_REQUESTED** [review]
change the name of the folder and the file to 'Card' with an upper letter, otherwise yarn wont run

**Review by claraabk — CHANGES_REQUESTED** [review]
the font is chosen as 'Valera Round' and is supposed to be 'Varela Round'

**Review by claraabk — DISMISSED** [review]
nice

**Review by GUIBA4 — DISMISSED** [review]

**Pull request merged**
